name: nonzero
description: Non Zero
version: 0.0.1+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  get_it: ^7.2.0
  dafluta: ^4.2.0
  url_strategy: ^0.2.0
  google_sign_in: ^5.4.1
  
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  dalocale: ^2.4.2
  daassets: ^1.3.2
  daunused: ^1.3.0
  dapublock: ^1.0.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true