name: nonzero
description: Non Zero
version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  get_it: ^7.2.0
  dafluta: ^3.6.0
  url_strategy: ^0.2.0
  google_sign_in: ^5.3.3
  
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  dalocale: ^2.4.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true