name: nonzero
description: Non Zero
version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  get_it: ^7.2.0
  dafluta: ^3.3.0
  url_launcher: ^6.1.3
  shared_preferences: ^2.0.15
  
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true