name: nonzero
description: Non Zero
version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: ^0.13.4
  get_it: ^7.2.0
  dafluta: ^2.9.0
  url_launcher: ^6.0.20
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13 
  
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true